#-------------------------------
# General Site Settings

title: Eda Gjergo
logo: 
author: Eda Gjergo
description: Astrophysics Postdoc
email: eda.gjergo@gmail.com
github: https://github.com/egjergo 
youtube: https://www.youtube.com/user/TheCosmicWeb/
copyright: Copyright &copy; 2022 by Eda Gjergo

menu:
- {name: About, link: '/about'}
#- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: G-KFM7WF17YV


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Eda Gjergo <br> Astrophysics Postdoc

social:
- {icon: "ti-github", link: "egjergo"}
- {icon: "ti-twitter", link: "eda_gjergo"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I'm an astrophysics postdoc at Wuhan University (China).
  Prior to this, I earned a Physics Ph.D. in Trieste (Italy), 
  two B.S. in Applied Mathematics and Physics at IIT (Chicago, IL, USA).
  
  My research interests include galactic chemical evolution, dust modeling, 
  cosmological simulations, interstellar and intracluster medium, 
  supernova cosmology, and dark energy models. 
blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
#work-process:
#  - title : "Research and Plan"
#    icon : "assets/images/icons/plan.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#  - title : "Design and Develop"
#    icon : "assets/images/icons/design.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#  - title : "Deliver"
#    icon : "assets/images/icons/print.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
#team:
#  - title : "Jack Schenziwe"
#    image : "assets/images/team/member-1.png"
#    designation : "Project Manager"
    
#  - title : "Julias Carlie"
#    image : "assets/images/team/member-2.png"
#    designation : "Web Developer"
    
#  - title : "John Doe"
#    image : "assets/images/team/member-3.png"
#    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Research Intersts
skills:
- {name: Galactic Chemical and Dust Evolution, color: '#fdb157', value: '60%'}
- {name: Interstellar Medium, color: '#9473e6', value: '20%'}
- {name: Cosmological Simulations, color: '#bdecf6', value: '15%'}
- {name: Supernova Cosmology, color: '#ffbcaa', value: '5%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior Research Assistant, icon: 'icon-1.png', date: '2011 - 2015', organization: 'Argonne National Lab (Chicago, IL, USA)'}
- {name: Research Assistant, icon: 'icon-2.png', date: '2015 - 2019', organization: 'Osservatorio Astronomico INAF (Trieste, Italy)'}
- {name: Postdoctoral Scholar, icon: 'icon-3.png', date: '2019 - Present', organization: 'Wuhan University (Wuhan, China)'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Ph.D. in Physics, date: '2019', organization: 'Università degli Studi di Trieste (Trieste, Italy)'}
- {name: B.S. in Physics, date: '2014', organization: 'Illinois Institute of Technology (Chicago, IL, USA)'}
- {name: B.S. in Applied Mathematics, date: '2014', organization: 'Illinois Institute of Technology (Chicago, IL, USA)'}
- {name: International Baccalaureate, date: '2008', organization: 'United World College (Duino, Italy)'}


#-------------------------------
# Services Section

#services-title: Services
#services:
#- {
#    name: UI Design,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation : "CEO, Funder"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: eda.gjergo@gmail.com
